data_params:
  noisy_path: "../NRSER2/data/urgent2024/noisy_wav"
  enhanced_path: "../NRSER2/data/urgent2024/SEMamba"
  list_file: "../NRSER2/data/urgent2024/txtfiles/config.txt"
  out_path: "data/urgent2024/corrected_SEMamba_nb_wav"

model_params:
  model: 'TF'

objective_params: # (model, weight_coef) tuples
  quality:
    - [scoreq, -1]
    # - [nisqa, -1]
    # - [audiobox.ce, -1]
    # - [audiobox.pq, -1]
  robustness:
    - [whisper-embsim, 1]
    # - [wavlm-embsim, 1]

optimizer_params:
  steps: 20
  lr: 0.1
  weight_decay: 0.1
  kernel_size: 801