data_params:
  noisy_path: data/noisy_path
  enhanced_path: data/enhanced_path
  list_file: data/a.txt
  out_path: data/out_path

objective_params:
  quality:
    - scoreq
    - nisqa
    - audiobox.ce
    - audiobox.pq
  robustness:
    - whisper-embsim
    # - wavlm-embsim
  
  quality_coefs: [1, 1]
  robustness_coefs: [1]

optimizer_params:
  steps: 20
  lr: 0.1
  weight_decay: 0.1
  kernel_size: 201